apiVersion: v1
kind: Service
metadata:
  name: solo-leveling-ui
spec:
  selector:
    app: solo-leveling-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP